import { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Login | Cattle Farm',
    description: 'Generated by create next app',
};

export default function Layout({ children }: { children: ReactNode }) {
    return (
        <div className="bg-[#fbfff1] h-screen flex items-center justify-center w-full">
            {children}
        </div>
    );
}
