import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const mahfujRumaysa = localFont({
    src: [
        {
            path: '/fonts/FN-Mahfuj-Rumaysa.ttf',
            weight: '400',
            style: 'normal',
        },
    ],
    variable: '--font-mahfuj-rumaysa',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Dashboard | Cattle Farm',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="bn">
            <body className={`${mahfujRumaysa.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
