import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
    title: 'Dashboard | Cattle Farm',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="bn">
            <head>
                {/* Font Credentials */}
                <link
                    href="https://api.fontshare.com/v2/css?f[]=satoshi@1,2&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className={`antialiased`}>
                {children}
                <Toaster position="bottom-right" reverseOrder={false} />
            </body>
        </html>
    );
}
